python baselines/train.py \
  --model_type EVO \
  --task_name tf_m \
  --eval_metrics mcc \
  --num_labels 13 \
  --train-dataset-path /home/data/chenzihong/code/BioMLLM_V2/tmp/train_TF-M_task.parquet \
  --eval-dataset-path /home/data/chenzihong/code/BioMLLM_V2/tmp/test_TF-M_task.parquet \
  --dna-rna-model-path evo2_1b_base  \
  --dna-rna-k-tokens 1024 \
  --protein-model-path /share/appspace_data/shared_groups/yzwl_chenzh_ChenZihong_Share/base_llm/esm2_t33_650M_UR50D/ \
  --protein-k-tokens 1024 \
  --output_dir ./ckpt_hf/tf_m \
  --num_train_epochs 5 \
  --per_device_train_batch_size 64 \
  --per_device_eval_batch_size 32 \
  --learning_rate 2e-5 \
  --warmup_ratio 0 \
  --logging_steps 50 \
  --do_eval \
  --eval_strategy epoch \
  --save_strategy epoch \
  --dataloader_num_workers 8 \
  --load_best_model_at_end \
  --metric_for_best_model eval_mcc \
  --report_to none \
