python baselines/train.py \
  --model_type NT \
  --task_name ncrna \
  --eval_metrics acc \
  --num_labels 13 \
  --train-dataset-path /share/appspace_data/shared_groups/yzwl_chenzh_ChenZihong_Share/omics_data/CotExp/woCOT/NcRNA/train_NcRNA_task.parquet  \
  --eval-dataset-path /share/appspace_data/shared_groups/yzwl_chenzh_ChenZihong_Share/omics_data/CotExp/woCOT/NcRNA/val_NcRNA_task.parquet \
  --dna-rna-model-path /share/appspace_data/shared_groups/yzwl_chenzh_ChenZihong_Share/base_llm/nucleotide-transformer/  \
  --dna-rna-k-tokens 1024 \
  --protein-model-path /share/appspace_data/shared_groups/yzwl_chenzh_ChenZihong_Share/base_llm/esm2_t33_650M_UR50D/ \
  --protein-k-tokens 1024 \
  --output_dir ./ckpt_hf/ncrna \
  --num_train_epochs 5 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 8 \
  --learning_rate 1e-4 \
  --warmup_ratio 0.1 \
  --logging_steps 50 \
  --do_eval \
  --eval_strategy epoch \
  --save_strategy epoch \
  --dataloader_num_workers 8 \
  --load_best_model_at_end \
  --metric_for_best_model eval_acc \
  --report_to none \
  --label2id_path baselines/data/ncrna_labels.json \
  --multi_label \
